# Generated by Django 3.2.18 on 2023-03-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='unit_title',
        ),
    ]
